### ISSUE TITLE
No items in cart

### ISSUE THREAD

**Issue by darkcherrycreative** [mativiscusso/ian-ecommerce#14]
This looks great and very promising, vendure is a great platform. I've added a test product, but when i try and add an item to the cart the shopping cart still appears to be empty. Is this something you're aware of?

**Comment by mativiscusso** [comment]
Yes, do yo need to be loggued to add items to the cart. I'm will work on this issue so that items can be added to the cart as guest.

**Comment by mativiscusso** [comment]
Hi @darkcherrycreative, this problem is done. Check the main branch to verify.
